# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[manager]
prepend_keymap = [
  # [boydaihungst/simple-tag.yazi](https://github.com/boydaihungst/simple-tag.yazi)
  { on = [
    '"',
  ], run = "plugin simple-tag -- toggle-tag", desc = "Toggle a tag (press any key)" },
  { on = [
    "'",
  ], run = "plugin simple-tag -- toggle-tag --key=*", desc = "Toggle tag with fixed tag key = *" },
  { on = [
    "t",
    "e",
  ], run = "plugin simple-tag -- edit-tag ", desc = "Edit tag(s) (input box)" },
  { on = [
    "t",
    "c",
  ], run = "plugin simple-tag -- clear", desc = "Clear all tags from selected or hovered files" },
  { on = [
    "t",
    "f",
  ], run = "plugin simple-tag -- filter", desc = "Filter files/folders by a tag (press any key)" },

  # toggle & visual mode
  { on = "v", run = "toggle_all", desc = "Invert selection of all files" },
  { on = "V", run = "visual_mode", desc = "Enter visual mode (selection mode)" },
  { on = "<C-a>", run = "noop" },
  { on = "<C-r>", run = "noop" },

  # disable keymaps
  { on = [
    "g",
    "d",
  ], run = "noop" },
  { on = "t", run = "noop" },
  { on = "1", run = "noop" },
  { on = "2", run = "noop" },
  { on = "3", run = "noop" },
  { on = "4", run = "noop" },
  { on = "5", run = "noop" },
  { on = "6", run = "noop" },
  { on = "7", run = "noop" },
  { on = "8", run = "noop" },
  { on = "9", run = "noop" },
  { on = "[", run = "noop" },
  { on = "]", run = "noop" },
  { on = "{", run = "noop" },
  { on = "}", run = "noop" },
  { on = "<S-PageUp>", run = "noop" },
  { on = "<S-PageDown>", run = "noop" },
  { on = "<PageUp>", run = "noop" },
  { on = "<PageDown>", run = "noop" },

]
