# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/theme-dark.toml

[filetype]
rules = [
  # Images
  # { mime = "image/*", fg = "yellow" },
  # Media
  # { mime = "{audio,video}/*", fg = "magenta" },
  # Archives
  # { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },
  # Documents
  # { mime = "application/{pdf,doc,rtf}", fg = "cyan" },
  # Empty files
  # { mime = "inode/empty", fg = "red" },
  # Special files
  { name = "*", is = "orphan", fg = "red" },
  { name = "*", is = "exec", fg = "green" },
  # Dummy files
  { name = "*", is = "dummy", fg = "red" },
  { name = "*/", is = "dummy", fg = "red" },
  # Fallback
  # { name = "*", fg = "white" },
  { name = "*/", fg = "blue" },
]
