[greenclip]
history_file = "/home/frla/.cache/greenclip.history"
image_cache_directory = "/tmp/greenclip"
blacklisted_applications = []
enable_image_support = true
max_history_length = 10000
max_selection_size_bytes = 0
trim_space_from_selection = true
use_primary_selection_as_input = false
static_history =
[
  '(´·ω·`)',
]
