#!/usr/bin/env sh

SFEED_DIR="$HOME/.local/share/sfeed"
SFEED_FEED_DIR="$SFEED_DIR/feeds"
SFEED_HTML_DIR="$SFEED_DIR/html"
SFEED_UNREAD_FILE="$SFEED_DIR/unread"
SFEED_READ_FILE="$SFEED_DIR/read"

usage() {
  echo "usage: $(basename "$0") [get|browser|find]"
}

filter_unread() {
  awk -F'\t' '
    FNR == NR {
      read[$0]
      next
    }
    !($3 in read) {
      fname = FILENAME
      sub(".*/", "", fname)
      $2 = "[" fname "] " $2
      out = $1
      for (i = 2; i <= NF; i++) {
        out = out "\t" $i
      }
      print out
    }
  ' "$SFEED_READ_FILE" "$SFEED_FEED_DIR"/* >"$SFEED_UNREAD_FILE"
}

generate_html_and_markread() {
  cat <<EOF
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<title>sfeed</title>
<link rel="stylesheet" href="../style.css">
</head>
<body>
<ul class="feed">
EOF
  awk -F'\t' -v read="$SFEED_READ_FILE" '
    {
      cmd = "date -d @" $1 " +\"%Y-%m-%d %H:%M\""
      cmd | getline t
      close(cmd)
      printf "  <li class=\"item\">\n"
      printf "    <time class=\"date\">%s</time>\n", t
      printf "    <a class=\"title\" href=\"%s\">%s</a>\n", $3, $2
      printf "  </li>\n"
      print $3 >> read
    }
  ' "$SFEED_UNREAD_FILE"
  cat <<EOF
</ul>
</body>
</html>
EOF
}

open_with_browser() {
  mkdir -p "$SFEED_HTML_DIR"
  timestamp=$(date +%Y%m%d%H%M%S)
  html_file="$SFEED_HTML_DIR/sfeed-${timestamp}.html"
  generate_html_and_markread >"$html_file"
  sort -u "$SFEED_READ_FILE" -o "$SFEED_READ_FILE"
  "$BROWSER" "$html_file"
}

find() {
  if [ -z "$1" ]; then
    echo "usage: $(basename "$0") find url"
    exit 1
  fi
  curl -sL "$1" | sfeed_web | cut -f1
}

[ -z "$1" ] && usage && exit 1

case "$1" in
get)
  sfeed_update
  filter_unread
  ;;
browser)
  filter_unread
  open_with_browser
  filter_unread
  ;;
find)
  find "$2"
  ;;
*)
  usage
  exit 1
  ;;
esac
